### ISSUE TITLE
Code f2c.py is ready for grading!

### ISSUE THREAD

**Issue by nmlund-matc** [madisoncollege-it-programs/python-scripting-nmlund-matc#11] opened 2022-10-31 03:41 UTC

**Comment by cethenmc** [comment] 2022-11-11 17:51
Hi, Nick.  Only one submission was required for week 9.  I will add this in both issue tickets you created.  We are holding at a 6 of 8 for now.  The unchecked boxes are what is missing.  You are welcome to submit corrected versions for full credit.

I will also add that the tempconversion.py was intended to be run through the "main()" function, which is why the part title looks like this:  "Script 2 - Temp Conversion (**Main**)."  It was not super clear, so I am not deducting points.  However, since you are modifying the other pieces, you may want to consider modifying your tempconversion.py script to run that way.

![image](https://user-images.githubusercontent.com/112707666/201397479-180553e1-846d-4ba4-b6e0-362aecfc0dd6.png)

**Comment by cethenmc** [comment] 2022-12-16 17:20
Closing.  Time expired.

**Closed by cethenmc** 2022-12-16 17:20 UTC
