### ISSUE TITLE
Code tempconversion.py is ready for grading!

### ISSUE THREAD

**Issue by nmlund-matc** [madisoncollege-it-programs/python-scripting-nmlund-matc#12] opened 2022-10-31 03:41 UTC

**Comment by cethenmc** [comment] 2022-11-02 16:53
Hi, Nick.  See both tickets for feedback.  I am recording a 6 of 8 for now, with eligibility for full credit.  Please reply to these issue tickets when repushed to GitHub.

You should be printing the return value in this script (instead of letting the print in f2c show up here).  See other Issue ticket for detail.

**Comment by cethenmc** [comment] 2022-11-02 17:54
I will also add that the tempconversion.py was intended to be run through the "main()" function, which is why the part title looks like this:  "Script 2 - Temp Conversion (**Main**)."  It was not super clear, so I am not deducting points.  However, since you are modifying the other pieces, you may want to consider modifying your tempconversion.py script to run that way.

**Comment by cethenmc** [comment] 2022-12-08 18:45
Hi, Nick.  Besides the opportunity to move this from a 6 to an 8.  I see the Weeks 10 through 12 remain at large.  Do you think you will do those before the final or after the final?  Thanks. ~Chris

**Comment by cethenmc** [comment] 2022-12-16 17:20
Closing.  Time expired.

**Closed by cethenmc** 2022-12-16 17:20 UTC
